Repository mesosphere/dcos-commons, pull requests merged in 2018-10, with the labels that each got.

#2698 Revert "[DCOS-41803] Overwrite the CLI in docker image with an old CL…
  Dockerfile
  tools/dcos_login.py
Labels: backport, bug, ready for review, tools

#2694 DCOS-42539 (backport) Improve recovery config ID selection
  frameworks/kafka/universe/config.json
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirementTestUtils.java
Labels: backport

#2706 [DCOS-42820] Revert "Local Profile Mount Volume Support. (#2632)"
  frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java
  sdk/scheduler/build.gradle
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PodSpecsCannotUseUnsupportedFeatures.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/Capabilities.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/MesosResourcePool.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorResourceMapper.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceLabels.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceMapperUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskResourceMapper.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSet.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultVolumeSpec.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/ValidationUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/VolumeSpec.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/RawVolume.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/TaskVolumesCannotChangeTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/VerifyVolumePathTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/MesosResourcePoolTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceBuilderTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/UnreserveOfferRecommendationTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorVolumesTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStageTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/PodInstanceRequirementTestUtils.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultPodSpecTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultTaskSpecTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultVolumeSpecTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/ZoneValidatorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/ResourceTestUtils.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TestConstants.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TestPodFactory.java
  sdk/scheduler/src/test/resources/valid-profile-mount-volume.yml
Labels: bug

#2705 [DCOS-42818] Use non-foldered name for HDFS kerberos test
  frameworks/hdfs/tests/test_default_kerberos_setup.py
Labels: ready for review

#2702 [DCOS-29502] Add default principal pattern for HDFS
  frameworks/hdfs/src/main/dist/core-site.xml
  frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HDFSAuthEnvContainer.java
  frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/HDFSUserAuthMapperBuilder.java
  frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java
  frameworks/hdfs/src/test/java/com/mesosphere/sdk/hdfs/scheduler/HDFSUserAuthMapperBuilderTest.java
  frameworks/hdfs/tests/auth.py
  frameworks/hdfs/tests/test_default_kerberos_setup.py
Labels: backport, ready for review

#2677 [DCOS-41674] Add test to check envvars under restart
  frameworks/cassandra/tests/test_sanity.py
  frameworks/helloworld/src/main/dist/sidecar.yml
  frameworks/helloworld/tests/test_sanity.py
  frameworks/helloworld/tests/test_sidecar.py
Labels: ready for review

#2511 [DCOS-37660] Add initial diagnostics script.
  .dockerignore
  .gitignore
  .pylintrc
  testing/sdk_cmd.py
  testing/sdk_hosts.py
  tools/diagnostics/CHANGELOG.md
  tools/diagnostics/README.md
  tools/diagnostics/agent.py
  tools/diagnostics/base_tech_bundle/__init__.py
  tools/diagnostics/base_tech_bundle/cassandra_bundle.py
  tools/diagnostics/base_tech_bundle/elastic_bundle.py
  tools/diagnostics/base_tech_bundle/hdfs_bundle.py
  tools/diagnostics/base_tech_bundle/kafka_bundle.py
  tools/diagnostics/bundle.py
  tools/diagnostics/config.py
  tools/diagnostics/create_service_diagnostics_bundle.py
  tools/diagnostics/create_service_diagnostics_bundle.sh
  tools/diagnostics/full_bundle.py
  tools/diagnostics/service_bundle.py
Labels: ready for review, tools

#2703 [DCOS-42770] Wait until no deployments are queued after deletion
  testing/sdk_marathon.py
Labels: ready for review

#2692 [DCOS-29171] Move topic operations to kafka testing client
  frameworks/kafka/tests/client.py
  frameworks/kafka/tests/test_kerberos_auth.py
  frameworks/kafka/tests/test_kerberos_authz.py
  frameworks/kafka/tests/test_kerberos_authz_no_acls_required.py
  frameworks/kafka/tests/test_overlay.py
  frameworks/kafka/tests/test_rack_awareness.py
  frameworks/kafka/tests/test_sanity.py
  frameworks/kafka/tests/test_ssl_auth.py
  frameworks/kafka/tests/test_ssl_kerberos_auth.py
  frameworks/kafka/tests/test_ssl_kerberos_authz.py
  frameworks/kafka/tests/test_ssl_kerberos_custom_domain_auth.py
  frameworks/kafka/tests/test_tls.py
  frameworks/kafka/tests/test_toggle_security.py
  frameworks/kafka/tests/test_topics.py
  frameworks/kafka/tests/test_utils.py
  frameworks/kafka/tests/test_zookeeper.py
  frameworks/kafka/tests/test_zookeeper_auth.py
  frameworks/kafka/tests/test_zookeeper_authz.py
Labels: ready for review

#2732 [DCOS-43947] Update JRE to 8u192 to address CVEs (#2728)
  tools/universe/package_builder.py
Labels: backport, ready for review

#2738 [DCOS-44086] Bump snapshot version for 0.42.5 release
  build.gradle
Labels: ready for review

#2739 [DCOS-44265] Remove python-apt from frozen_requirements.txt
  frozen_requirements.txt
Labels: ready for review
