Repository mesosphere/dcos-commons, pull requests merged in 2018-02, with the labels that each got.

#2231 INFINITY-3107 Trim 'beta-' prefix for default service name in CLI (#2217)
  cli/commands.go
  cli/config/config.go
Labels: backport

#2156 Add elastic-2.1.2-5.6.5-beta release notes.
  frameworks/elastic/docs/release-notes.md
Labels: documentation, ready for review

#2205 [INFINITY-2837] readiness should be checked at startup
  frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/SchedulerRestartServiceTest.java
  frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactory.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactoryTest.java
Labels: ready for review

#2230 CASSANDRA-672 Remove unused s3config.json (#2224)
  frameworks/cassandra/src/main/dist/s3config.json
  frameworks/cassandra/src/main/dist/svc.yml
Labels: backport

#2212 [INFINITY-2725] fix kdc soak issues
  testing/sdk_auth.py
  tools/kdc/kdc.py
Labels: ready for review

#2242 Merge pull request #2205 from master
  frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/SchedulerRestartServiceTest.java
  frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactory.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactoryTest.java
Labels: backport, ready for review

#2246 INFINITY-3153 Support HTTP[S]_PROXY/NO_PROXY envvars (#2241)
  cli/client/http.go
Labels: backport

#2237 INFINITY-2974: Backport binary secrets documentation update.
  docs/pages/ops-guide/overview.md
Labels: backport, documentation, ready for review

#2238 INFINITY-3039: Add Cassandra TLS toggling tests. (#2177)
  frameworks/cassandra/tests/test_tls.py
  frameworks/cassandra/tests/test_toggle_tls.py
Labels: backport, ready for review, tests

#2247 INFINITY-3167: Add LIBMESOS_URI envvar removed by accident
  frameworks/cassandra/universe/marathon.json.mustache
Labels: ready for review

#2221 [INFINITY-3111] Gracefully handle invalid placement constraints
  frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceTest.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValid.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AndRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParser.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/OrRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/PlacementRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValidTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRuleTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParserTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/TestPlacementUtils.java
Labels: blocker, ready for review

#2251 Integrate ops guide material into per-service docs
  docs/pages/_includes/services/common-operations.md
  docs/pages/_includes/services/diagnostic-tools.md
  docs/pages/_includes/services/overview.md
  docs/pages/_includes/services/troubleshooting.md
  docs/pages/ops-guide/index.md
  docs/pages/ops-guide/troubleshooting.md
  frameworks/cassandra/docs/common-operations.md
  frameworks/cassandra/docs/diagnostic-tools.md
  frameworks/cassandra/docs/overview.md
  frameworks/elastic/docs/common-operations.md
  frameworks/elastic/docs/diagnostic-tools.md
  frameworks/elastic/docs/overview.md
  frameworks/hdfs/docs/common-operations.md
  frameworks/hdfs/docs/diagnostic-tools.md
  frameworks/hdfs/docs/overview.md
  frameworks/kafka/docs/common-operations.md
  frameworks/kafka/docs/diagnostic-tools.md
  frameworks/kafka/docs/overview.md
  frameworks/template/docs/common-operations.md
  frameworks/template/docs/diagnostic-tools.md
  frameworks/template/docs/overview.md
Labels: backport

#2248 [INFINITY-2725] fix kdc soak issues (#2212)
  testing/sdk_auth.py
  tools/kdc/kdc.py
Labels: backport, ready for review

#2252 Report task status correctly for unprepared paused/resumed tasks
  sdk/scheduler/src/main/java/com/mesosphere/sdk/http/PodResource.java
Labels: backport

#2254 [INFINITY-3111] Gracefully handle invalid placement constraints (#2221)
  frameworks/template/src/test/java/com/mesosphere/sdk/template/scheduler/ServiceTest.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValid.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/AndRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParser.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/OrRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/PlacementRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/PlacementRuleIsValidTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/InvalidPlacementRuleTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/MarathonConstraintParserTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/placement/TestPlacementUtils.java
Labels: backport

#2255 [INFINITY-3172] Fix sidecar refinement / MOUNT volume reuse (#2207)
  frameworks/helloworld/src/main/dist/examples/pre-reserved-sidecar.yml
  frameworks/helloworld/tests/test_pre_reserved_sidecar.py
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorResourceMapper.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluationUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceLabels.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskResourceMapper.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStage.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/VolumeEvaluationStageTest.java
Labels: backport

#2137 [INFINITY-3035] toggle kafka security settings
  frameworks/kafka/docs/limitations.md
  frameworks/kafka/tests/auth.py
  frameworks/kafka/tests/conftest.py
  frameworks/kafka/tests/test_toggle_security.py
Labels: ready for review, tests

#2266 INFINITY-2949 Add instructions for debugging uninstall (#2257)
  docs/pages/_includes/services/uninstall.md
Labels: backport

#2268 [INFINITY-3195] Fix security toggle tests
  frameworks/kafka/tests/test_toggle_security.py
Labels: ready for review, tests

#2264 [INFINITY-3035] Add test for toggling Kafka security settings
  frameworks/kafka/docs/limitations.md
  frameworks/kafka/tests/auth.py
  frameworks/kafka/tests/conftest.py
  frameworks/kafka/tests/test_toggle_security.py
Labels: backport, ready for review, tests

#2272 [INFINITY-3115] Remove update strategy
  frameworks/hdfs/src/main/dist/svc.yml
  frameworks/hdfs/universe/config.json
  frameworks/hdfs/universe/marathon.json.mustache
Labels: bug, hdfs

#2275 [INFINITY-3214] Nullify default value for HDFS authz mapping
  frameworks/hdfs/universe/config.json
Labels: hdfs, security

#2284 [INFINITY-3222] Backport nullifying default HDFS authz mapping
  frameworks/hdfs/universe/config.json
Labels: backport, hdfs

#2287 Upgrade base Cassandra version to 3.0.16
  frameworks/cassandra/universe/marathon.json.mustache
  frameworks/cassandra/universe/resource.json
Labels: backport

#2273 [INFINITY-2835] Allow package name to be overridden with an envvar
  tools/release_builder.py
Labels: ready for review

#2288 [INFINITY-2835][BACKPORT] Allow package name to be overridden with a PACKAGE_NAME environment variable.
  tools/release_builder.py
Labels: backport, ready for review

#2281 Catch up docs to master, support dcos-docs-site import
  docs/README.md
  docs/pages/_data/services/hdfs.yml
  docs/pages/_data/services/template.yml
  docs/pages/_includes/services/common-operations.md
  docs/pages/_includes/services/diagnostic-tools.md
  docs/pages/_includes/services/install1.md
  docs/pages/_includes/services/install2.md
  docs/pages/_includes/services/managing.md
  docs/pages/_includes/services/overview.md
  docs/pages/_includes/services/troubleshooting.md
  docs/pages/developer-guide.md
  docs/pages/img/ops-guide-marathon-app-list.png
  docs/pages/img/ops-guide-marathon-config-env.png
  docs/pages/img/ops-guide-marathon-config-section.png
  docs/pages/img/ops-guide-task-info.png
  docs/pages/img/services/ops-guide-agent.png
  docs/pages/img/services/ops-guide-all-tasks.png
  docs/pages/img/services/ops-guide-edit-scheduler.png
  docs/pages/img/services/ops-guide-exhibitor-delete-task.png
  docs/pages/img/services/ops-guide-exhibitor-view-taskstatus.png
  docs/pages/img/services/ops-guide-framework-tasks-marathon.png
  docs/pages/img/services/ops-guide-framework-tasks-service.png
  docs/pages/img/services/ops-guide-frameworks-list.png
  docs/pages/img/services/ops-guide-mesos-tasks-reconfigured.png
  docs/pages/img/services/ops-guide-scheduler-sandbox.png
  docs/pages/img/services/ops-guide-task-sandbox.png
  docs/pages/operations-guide.md
  frameworks/cassandra/docs/file_list.txt
  frameworks/cassandra/docs/install.md
  frameworks/elastic/docs/elastic-x-pack.md
  frameworks/elastic/docs/file_list.txt
  frameworks/elastic/docs/install.md
  frameworks/hdfs/docs/install.md
  frameworks/hdfs/docs/quick-start.md
  frameworks/hdfs/universe/package.json
  frameworks/kafka/docs/install.md
  frameworks/template/docs/install.md
Labels: backport, documentation

#2308 [INFINITY-3248] Backport #2295 (mesosphere/INFINITY-3248-resource-sets-docs)
  docs/pages/developer-guide.md
Labels: backport, documentation

#2314 [BACKPORT] Fix spelling mistakes (#2311)
  frameworks/cassandra/docs/security.md
  frameworks/hdfs/docs/security.md
  frameworks/kafka/docs/security.md
Labels: backport, ready for review

#2304 [INFINITY-3127] Cleanup HDFS service settings docs
  frameworks/hdfs/docs/install.md
Labels: documentation, ready for review

#2313 [INFINITY-3280] Regression in advertised listeners behavior
  frameworks/kafka/setup-helper/setup_helper.go
  frameworks/kafka/setup-helper/setup_helper_test.go
  frameworks/kafka/universe/config.json
Labels: ready for review

#2318 [INFINITY-3127][BACKPORT] update hdfs service docs
  frameworks/hdfs/docs/install.md
Labels: backport, documentation, ready for review
