Repository mesosphere/dcos-commons, pull requests merged in 2018-07, with the labels that each got.

#2553 [DCOS-38688] Fix upgrade for Cassandra for non-default rack setting
  frameworks/cassandra/src/main/dist/cassandra-rackdc.properties
  frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java
  frameworks/cassandra/tests/test_racks.py
  frameworks/cassandra/universe/config.json
  frameworks/cassandra/universe/marathon.json.mustache
Labels: bug, ready for review, wip

#2540 DCOS-37673: Upstream buildchain modifications from edgelb
  tools/airgap_linter.py
  tools/build_go_exe.sh
Labels: ready for review, tools

#2532 [TOOLS][TESTS] Add tooling for running flake8 as a pre-commit hook and in CI
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
  TESTING.md
  test_requirements.txt
  testing/sdk_diag.py
  testing/sdk_hosts.py
  testing/sdk_install.py
  testing/sdk_jobs.py
  testing/sdk_metrics.py
  testing/sdk_plan.py
  testing/sdk_security.py
  testing/sdk_tasks.py
  testing/sdk_upgrade.py
  tools/ci/checks/get_applicable_changes.py
  tools/ci/checks/get_base_branch.sh
  tools/ci/checks/run_flake8_checks.sh
  tools/ci/checks/run_pylint_checks.sh
  tools/ci/steps/check_python_files.sh
  tools/distribution/init
Labels: ready for review, tools

#2558 [DCOS_OSS-3555] Use a valid boolean value for Kafka envvar
  frameworks/kafka/universe/marathon.json.mustache
Labels: ready for review

#2559 [DCOS-37673][BACKPORT] Upstream buildchain modifications from edgelb.
  tools/airgap_linter.py
  tools/build_go_exe.sh
Labels: backport, ready for review, tools

#2561 [TOOLS][TESTS][BACKPORT] Add tooling for running flake8 in CI (#2532)
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
  TESTING.md
  test_requirements.txt
  testing/sdk_diag.py
  testing/sdk_hosts.py
  testing/sdk_install.py
  testing/sdk_jobs.py
  testing/sdk_metrics.py
  testing/sdk_plan.py
  testing/sdk_tasks.py
  testing/sdk_upgrade.py
  tools/ci/checks/get_applicable_changes.py
  tools/ci/checks/get_base_branch.sh
  tools/ci/checks/run_flake8_checks.sh
  tools/ci/checks/run_pylint_checks.sh
  tools/ci/steps/check_python_files.sh
  tools/distribution/init
Labels: backport, ready for review, tools

#2564 [DCOS-37640][BACKPORT] Update Kafka to 1.1.0 && update kafka-client (#2542)
  frameworks/kafka/client/Dockerfile
  frameworks/kafka/client/README.md
  frameworks/kafka/client/client-jaas.conf
  frameworks/kafka/client/client.properties
  frameworks/kafka/client/krb5.conf
  frameworks/kafka/client/start.sh
  frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java
  frameworks/kafka/tests/client.py
  frameworks/kafka/tests/test_zookeeper_authz.py
  frameworks/kafka/versions.sh
Labels: backport

#2556 [COPS-3222][DCOS-38688] Add pod replace test to HDFS TLS
  .pylintrc
  frameworks/cassandra/tests/test_tls.py
  frameworks/cassandra/tests/test_toggle_tls.py
  frameworks/elastic/tests/test_tls.py
  frameworks/hdfs/tests/test_sanity.py
  frameworks/hdfs/tests/test_tls.py
  frameworks/helloworld/tests/test_tls.py
  frameworks/kafka/tests/config.py
  frameworks/kafka/tests/test_tls.py
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStage.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java
  testing/sdk_recovery.py
  testing/security/transport_encryption.py
Labels: bug, ready for review

#2574 [DCOS-29208] Add post_push hook to add additional docker tags
  hooks/post_push
Labels: ready for review

#2576 [COPS-3222][DCOS-38688] Cassandra pod replace performs rolling update
  frameworks/cassandra/tests/test_tls.py
  testing/sdk_recovery.py
Labels: ready for review, tests

#2579 [DCOS-38379][TESTS] Remove all multiservice dynamic tests from smoke
  frameworks/helloworld/tests/test_multiservice_dynamic.py
Labels: blocker, tests

#2583 [TOOLS] Fix release with multiple "upgradeFrom"s.
  tools/release_builder.py
Labels: ready for review, tools

#2584 [TOOLS] Default upgrades_from to an empty string.
  tools/release_builder.py
Labels: ready for review, tools

#2585 [TOOLS] Filter empty strings and fix conditional.
  tools/release_builder.py
Labels: ready for review, tools

#2577 [COPS-3222][DCOS-38688] Ensure Mounts for TLS secrets are not duplicate
  .pylintrc
  frameworks/cassandra/tests/test_tls.py
  frameworks/cassandra/tests/test_toggle_tls.py
  frameworks/elastic/tests/test_tls.py
  frameworks/hdfs/tests/test_sanity.py
  frameworks/hdfs/tests/test_tls.py
  frameworks/helloworld/tests/test_tls.py
  frameworks/kafka/tests/config.py
  frameworks/kafka/tests/test_tls.py
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStage.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java
  testing/sdk_recovery.py
  testing/security/transport_encryption.py
Labels: backport, bug, ready for review

#2588 [TOOLS] Add -e and --envfile flags to test.sh to pass environment
  test.sh
Labels: ready for review, tools

#2591 [DCOS-38688] Add custom rack upgrade test
  frameworks/cassandra/tests/test_racks.py
Labels: ready for review, tests

#2594 [BACKPORT][TOOLS] Add -e and --envfile flags to test.sh to pass environment (#2588)
  test.sh
Labels: backport, ready for review

#2595 [DCOS-38688] Add custom rack upgrade test (#2591)
  frameworks/cassandra/tests/test_racks.py
Labels: ready for review

#2573 DCOS-38544 Add mono to multi zk data migration
  conftest.py
  frameworks/helloworld/src/main/dist/foobar_service_name.yml
  frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java
  frameworks/helloworld/tests/test_goal_states.py
  frameworks/helloworld/tests/test_mono_to_multi_migrate.py
  frameworks/helloworld/universe/config.json
  sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorLocker.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorPersister.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/curator/CuratorUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkConfig.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkRunner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/HealthResource.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ExecutorResourceMapper.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluator.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceLabels.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/ResourceMapperUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TaskResourceMapper.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/placement/MaxPerAttributeRule.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/multi/MultiServiceEventClient.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/multi/MultiServiceRunner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/multi/ServiceStore.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/yaml/YAMLToInternalMappers.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/state/ConfigStore.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/state/SchemaVersionStore.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStore.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/storage/MemPersister.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/storage/Persister.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/storage/PersisterCache.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/storage/PersisterUtils.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/curator/CuratorPersisterTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/http/endpoints/HealthResourceTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerRunnerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/multi/MultiServiceEventClientTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/multi/MultiServiceRunnerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/state/SchemaVersionStoreTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/storage/MemPersisterTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/storage/PersisterUtilsTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/SchedulerConfigTestUtils.java
  test.sh
  testing/sdk_cmd.py
  testing/sdk_diag.py
  testing/sdk_plan.py
  testing/sdk_tasks.py
  testing/sdk_upgrade.py
  tools/ci/test_runner.sh
  tools/universe/package_manager.py
Labels: ready for review

#2603 DCOS-39806 Fix TaskKiller-related flakes
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java
Labels: backport

#2604 [TOOLS] Make `sdk_diag._dump_task_logs_for_task` return int.
  testing/sdk_diag.py
Labels: ready for review, tools
