Repository mesosphere/dcos-commons, pull requests merged in 2018-08, with the labels that each got.

#2597 Enable black formatting checks in code checks
  .flake8
  .pre-commit-config.yaml
  TESTING.md
  pyproject.toml
  test_requirements.txt
  tools/ci/checks/run_pre_commit.sh
  tools/ci/checks/run_pylint_checks.sh
  tools/ci/steps/check_python_files.sh
Labels: ready for review, tools

#2611 DCOS-39979 Fix test_mono_to_multi_upgrade failures in 1.10 Open Cluster
  frameworks/helloworld/tests/test_mono_to_multi_migrate.py
  testing/sdk_upgrade.py
  testing/sdk_utils.py
Labels: ready for review

#2620 [DCOS-39326] Bump Gradle Versions Plugin to 0.20.0
  build.gradle
Labels: ready for review, tools

#2575 [DCOS-29527] add Kafka and HDFS testing client
  frameworks/hdfs/tools/docker-client/Dockerfile
  frameworks/hdfs/tools/docker-client/Makefile
  frameworks/hdfs/tools/docker-client/configure-environment.sh
  frameworks/hdfs/tools/docker-client/configure-hdfs.sh
  frameworks/hdfs/tools/docker-client/hdfsclient.json
  frameworks/hdfs/tools/docker-client/krb5.conf
  frameworks/kafka/client/Dockerfile
  frameworks/kafka/client/README.md
  frameworks/kafka/client/client-jaas.conf
  frameworks/kafka/client/client.properties
  frameworks/kafka/client/krb5.conf
  frameworks/kafka/client/start.sh
Labels: ready for review, tests, tools

#2621 Add .pre-commit-config.yaml to Docker image
  .dockerignore
  Dockerfile
Labels: ready for review

#2630 [DCOS-38370] Re-enable Kibana tests.
  frameworks/elastic/tests/test_sanity.py
  frameworks/elastic/tests/test_tls.py
Labels: elastic, ready for review, tests

#2617 [DCOS-40189] Fix HDFS test: test_kill_scheduler
  frameworks/hdfs/tests/test_sanity.py
  frameworks/helloworld/tests/tls/keystore/build.gradle
  testing/sdk_marathon.py
Labels: ready for review

#2631 [DCOS-40636][TOOLS] Add interactive testing note to TESTING.md
  TESTING.md
  test.sh
Labels: documentation, ready for review, tools

#2610 DCOS-38727 Add marathon constraints on helloworld scheduler
  frameworks/helloworld/tests/test_placement.py
  frameworks/helloworld/universe/config.json
  frameworks/helloworld/universe/marathon.json.mustache
  testing/sdk_tasks.py
Labels: ready for review

#2628 [DCOS-40457] Improve install failure detection
  frameworks/helloworld/src/main/dist/non_recoverable_state.yml
  frameworks/helloworld/tests/test_fast_failure.py
  frameworks/helloworld/universe/config.json
  testing/sdk_cmd.py
  testing/sdk_plan.py
  testing/sdk_tasks.py
Labels: tests
