Repository mesosphere/dcos-commons, pull requests merged in 2018-11, with the labels that each got.

#2726 [DCOS-41824] Enforce data service version under test
  frameworks/kafka/tests/config.py
  frameworks/kafka/tests/test_zookeeper_auth.py
  frameworks/kafka/tests/test_zookeeper_authz.py
  testing/sdk_install.py
  testing/sdk_package_registry.py
  testing/sdk_upgrade.py
Labels: ready for review

#2669 fix validate_images check
  tools/airgap_linter.py
Labels: bug

#2701 [DCOS-41744] add hello world metrics smoke test
  frameworks/cassandra/tests/test_sanity.py
  frameworks/elastic/tests/test_sanity.py
  frameworks/hdfs/tests/test_sanity.py
  frameworks/helloworld/tests/test_sanity.py
  frameworks/kafka/tests/test_sanity.py
  testing/sdk_cmd.py
  testing/sdk_metrics.py
Labels: ready for review, tests

#2748 [DCOS-44605] Filter sensitive environment keys and add file based secret support for frameworks
  frameworks/cassandra/universe/marathon.json.mustache
  frameworks/elastic/universe/marathon.json.mustache
  frameworks/hdfs/universe/marathon.json.mustache
  frameworks/helloworld/universe/marathon.json.mustache
  frameworks/kafka/universe/marathon.json.mustache
  sdk/bootstrap/main.go
  sdk/bootstrap/main_test.go
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
Labels: ready for review

#2751 [DCOS-44605] [Backport] Filter sensitive environment keys when printing to stdout/stderr
  sdk/bootstrap/main.go
  sdk/bootstrap/main_test.go
Labels: ready for review

#2749 [DCOS-41674][TESTS] Address review comments on restart tests for envvars
  frameworks/cassandra/tests/test_sanity.py
  frameworks/helloworld/src/main/dist/sidecar.yml
  frameworks/helloworld/tests/test_sidecar.py
Labels: ready for review

#2746 [DCOS-43952] [TOOLS] Install readwrite registry from bootstrap registry
  gradle/checkstyle/README.md
  test.sh
  testing/sdk_package_registry.py
Labels: ready for review

#2780 [DCOS-44001] Fix GitHub Security Warnings
  Dockerfile
  Dockerfile.base
  frozen_requirements.txt
Labels: ready for review

#2788 Add envvar to force hello world upgrade
  frameworks/helloworld/universe/marathon.json.mustache
Labels: ready for review, tools

#2761 [DCOS-29208] switch to mesosphere client images
  frameworks/hdfs/tests/config.py
  frameworks/hdfs/tests/test_kerberos_auth.py
  frameworks/kafka/tests/client.py
  frameworks/kafka/tests/test_active_directory_auth.py
  frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
Labels: ready for review

#2786 Update fixes to 'sdk_cmd.{_ssh(), _scp()}'
  testing/sdk_cmd.py
Labels: ready for review, tools
