Repository mesosphere/dcos-commons, pull requests merged in 2018-03, with the labels that each got.

#2303 [INFINITY-3047] Remove skipped test due to blocked ticket
  frameworks/helloworld/tests/test_zzzrecovery.py
Labels: ready for review

#2283 [INFINITY-2887] Update running of tests
  .dockerignore
  .gitignore
  Dockerfile
  TESTING.md
  sdk/testing/src/main/java/com/mesosphere/sdk/testing/CosmosRenderer.java
  test-runner.sh
  test.sh
  tools/ci/init
  tools/ci/launch_cluster.sh
  tools/ci/test_runner.sh
  tools/publish_aws.py
  tools/universe/package_builder.py
Labels: ready for review

#2321 INFINITY-3211 Fix flakes in TaskKiller unit tests (#2317)
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/TaskKiller.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/http/PodResourceTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/TaskKillerTest.java
  sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java
Labels: backport

#2327 [INFINITY-3285] Fix HDFS tests using client docker container
  frameworks/hdfs/tests/config.py
  frameworks/hdfs/tests/test_active_directory_auth.py
  frameworks/hdfs/tests/test_overlay.py
  frameworks/hdfs/tools/hdfsclient.json
Labels: blocker, ready for review, tests

#2328 [INFINITY-3285][BACKPORT] Fix HDFS tests using client docker container
  frameworks/hdfs/tests/config.py
  frameworks/hdfs/tests/test_active_directory_auth.py
  frameworks/hdfs/tests/test_overlay.py
  frameworks/hdfs/tools/hdfsclient.json
Labels: backport, blocker, ready for review, tests

#2325 [INFINITY-3047][BACKPORT] Re-enable tests that were blocked on a Mesos regression.
  frameworks/helloworld/tests/test_zzzrecovery.py
Labels: backport, ready for review, tests

#2336 INFINITY-3240 Support taskids with multiple entries (#2331)
  sdk/common/src/main/java/com/mesosphere/sdk/offer/CommonIdUtils.java
  sdk/common/src/test/java/com/mesosphere/sdk/offer/CommonIdUtilsTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/OfferEvaluatorTest.java
Labels: backport

#2340 [KAF-409] Add all the missing properties to the plumbing (#2323)
  frameworks/kafka/src/main/dist/server.properties.mustache
  frameworks/kafka/universe/config.json
  frameworks/kafka/universe/marathon.json.mustache
Labels: backport

#2326 [INFINITY-2887][BACKPORT] Update the way tests are run
  .dockerignore
  .gitignore
  Dockerfile
  TESTING.md
  sdk/testing/src/main/java/com/mesosphere/sdk/testing/CosmosRenderer.java
  test-runner.sh
  test.sh
  tools/ci/init
  tools/ci/launch_cluster.sh
  tools/ci/test_runner.sh
  tools/publish_aws.py
  tools/universe/package_builder.py
Labels: backport, blocked, ready for review

#2355 [BACKPORT] Derive Kafka version from a single source.
  frameworks/kafka/build.sh
  frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java
  frameworks/kafka/universe/marathon.json.mustache
  frameworks/kafka/universe/resource.json
  frameworks/kafka/versions.sh
Labels: backport, ready for review

#2354 [INFINITY-3133] Update HDFS readiness check to remove JMX dependency
  frameworks/hdfs/src/main/dist/svc.yml
Labels: bug, hdfs, ready for review

#2310 [INFINITY-3080] Use fine-grained permissions for DC/OS 1.11.
  frameworks/cassandra/tests/test_tls.py
  frameworks/cassandra/tests/test_toggle_tls.py
  frameworks/elastic/tests/test_tls.py
  frameworks/hdfs/tests/test_kerberos_auth.py
  frameworks/hdfs/tests/test_ssl_kerberos_auth.py
  frameworks/hdfs/tests/test_tls.py
  frameworks/kafka/tests/test_ssl_auth.py
  frameworks/kafka/tests/test_ssl_kerberos_auth.py
  frameworks/kafka/tests/test_tls.py
  frameworks/kafka/tests/test_toggle_security.py
  testing/sdk_security.py
  testing/security/transport_encryption.py
Labels: ready for review

#2361 [INFINITY-3321] Kibana CI install failure
  testing/sdk_repository.py
Labels: bug, tests, tools, wip

#2348 [ELASTIC-175] Make X-Pack install successfully.
  frameworks/elastic/tests/config.py
  frameworks/elastic/tests/test_sanity.py
  frameworks/elastic/universe-kibana/marathon.json.mustache
Labels: bug, ready for review

#2363 [INFINITY-3331] Fix cleaning up other framework's volumes
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/DefaultResourceCleaner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceCleaner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/ResourceUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerRunner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallResourceCleaner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/uninstall/UninstallScheduler.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceCleanerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/ResourceUtilsTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/AbstractSchedulerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallResourceCleanerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/DefaultServiceSpecTest.java
Labels: ready for review

#2372 [INFINITY-3331][Backport] Add integration test (#2365)
  frameworks/helloworld/tests/test_multistep_plan.py
  frameworks/helloworld/tests/test_resource_refinement.py
Labels: backport

#2371 [INFINITY-3080] Use fine-grained permissions for DC/OS 1.11. (#2310)
  frameworks/cassandra/tests/test_tls.py
  frameworks/cassandra/tests/test_toggle_tls.py
  frameworks/elastic/tests/test_tls.py
  frameworks/hdfs/tests/test_kerberos_auth.py
  frameworks/hdfs/tests/test_ssl_kerberos_auth.py
  frameworks/hdfs/tests/test_tls.py
  frameworks/kafka/tests/test_ssl_auth.py
  frameworks/kafka/tests/test_ssl_kerberos_auth.py
  frameworks/kafka/tests/test_tls.py
  frameworks/kafka/tests/test_toggle_security.py
  testing/sdk_security.py
  testing/security/transport_encryption.py
Labels: backport, ready for review

#2366 [BACKPORT][INFINITY-3133] Update HDFS readiness check to remove JMX d…
  frameworks/hdfs/src/main/dist/svc.yml
Labels: bug, hdfs, ready for review

#2360 [INFINITY-3329] Fix dryrun for package version and md5 hash
  tools/publish_aws.py
  tools/universe/package_builder.py
  tools/universe/package_manager.py
Labels: ready for review

#2376 [INFINITY-3329] Fix dryrun for package version and md5 hash (#2360)
  tools/publish_aws.py
  tools/universe/package_builder.py
  tools/universe/package_manager.py
Labels: backport, ready for review, tools

#2367 [INFINITY-3133] Added missing Kerberos auth for readiness check
  frameworks/hdfs/src/main/dist/svc.yml
  frameworks/hdfs/tests/test_kerberos_auth.py
Labels: bug, hdfs, ready for review

#2297 [INFINITY-3255] Cleanup HDFS client docker image
  frameworks/hdfs/docker-client/Dockerfile
  frameworks/hdfs/docker-client/configure-hdfs.sh
  frameworks/hdfs/tests/config.py
  frameworks/hdfs/tests/test_kerberos_auth.py
  frameworks/hdfs/tests/test_racks.py
  frameworks/hdfs/tests/test_ssl_kerberos_auth.py
  frameworks/hdfs/tools/docker-client/Dockerfile
  frameworks/hdfs/tools/docker-client/Makefile
  frameworks/hdfs/tools/docker-client/configure-environment.sh
  frameworks/hdfs/tools/docker-client/configure-hdfs.sh
  frameworks/hdfs/tools/docker-client/hdfsclient.json
  frameworks/hdfs/tools/docker-client/krb5.conf
  frameworks/hdfs/tools/krb5.conf
  testing/sdk_marathon.py
Labels: enhancement, hdfs, ready for review

#2359 [INFINITY-3328] Remove stub from ZooKeeper tests
  frameworks/kafka/tests/config.py
  frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
  frameworks/kafka/tests/test_zookeeper.py
  frameworks/kafka/tests/test_zookeeper_auth.py
Labels: ready for review, tests

#2383 Install botocore first to fix CI issue with dcos-launch (#2380)
  test_requirements.txt
Labels: backport, tools

#2381 [ELASTIC-177] Fix Kibana test failure on 1.9.
  frameworks/elastic/tests/config.py
  testing/sdk_cmd.py
Labels: ready for review, tests

#2387 Revert "[ELASTIC-177] Fix Kibana test failure on 1.9. (#2381)"
  frameworks/elastic/tests/config.py
  testing/sdk_cmd.py
Labels: ready for review, tests

#2382 [INFINITY-3328] Remove stub from ZooKeeper tests (#2359)
  frameworks/kafka/tests/config.py
  frameworks/kafka/tests/test_active_directory_zookeeper_auth.py
  frameworks/kafka/tests/test_zookeeper.py
  frameworks/kafka/tests/test_zookeeper_auth.py
Labels: backport, ready for review, tests

#2389 [INFINITY-3366] Skip all HDFS Kerberos tests on DC/OS 1.9
  frameworks/hdfs/tests/test_kerberos_auth.py
Labels: ready for review, tests

#2377 [BACKPORT][INFINITY-3133] Added missing Kerberos auth for readiness check (#2367)
  frameworks/hdfs/src/main/dist/svc.yml
  frameworks/hdfs/tests/test_kerberos_auth.py
Labels: ready for review

#2390 [ELASTIC-179] Fix Kibana command on 1.9 with localized change.
  frameworks/elastic/tests/config.py
Labels: ready for review, tests

#2378 Backport fix for FINISHED goal state checks
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactory.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DefaultStepFactoryTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TestPodFactory.java
Labels: backport

#2391 [BACKPORT] Backport infinity 3366 skip kerberos test on 1.9
  frameworks/hdfs/tests/test_kerberos_auth.py
Labels: ready for review

#2349 [ELASTIC-172] Add test that verifies that Kibana works against an ES cluster with TLS.
  frameworks/elastic/tests/config.py
  frameworks/elastic/tests/test_overlay.py
  frameworks/elastic/tests/test_sanity.py
  frameworks/elastic/tests/test_tls.py
  frameworks/hdfs/tests/test_tls.py
Labels: ready for review, security

#2401 [INFINITY-3203] Skip agent-based recovery tests on 1.9
  frameworks/helloworld/tests/test_zzzrecovery.py
Labels: ready for review, tests

#2407 [INFINITY-3363] Fix Kafka ZooKeeper reresolution test
  frameworks/kafka/tests/test_zookeeper.py
Labels: ready for review, tests

#2408 Correct JSON boolean
  frameworks/helloworld/tests/test_region_awareness.py
Labels: ready for review, tests

#2406 [INFINITY-3203] Skip agent-based recovery tests on 1.9 (#2401)
  frameworks/helloworld/tests/test_zzzrecovery.py
Labels: backport, ready for review, tests

#2405 [INFINITY-3396] Add service TLD top level override
  frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/CassandraSeedUtils.java
  frameworks/cassandra/src/main/java/com/mesosphere/sdk/cassandra/scheduler/Main.java
  frameworks/hdfs/src/main/java/com/mesosphere/sdk/hdfs/scheduler/Main.java
  frameworks/helloworld/src/main/dist/custom_tld.yml
  frameworks/helloworld/tests/test_custom_service_tld.py
  frameworks/helloworld/universe/config.json
  frameworks/helloworld/universe/marathon.json.mustache
  sdk/scheduler/src/main/java/com/mesosphere/sdk/http/EndpointUtils.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/http/endpoints/EndpointsResource.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/http/queries/EndpointsQueries.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStage.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/security/CertificateNamesGenerator.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/DefaultScheduler.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/http/EndpointUtilsTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/http/queries/EndpointsQueriesTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/CertificateNamesGeneratorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/TLSArtifactsGeneratorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/SchedulerConfigTestUtils.java
  sdk/testing/src/main/java/com/mesosphere/sdk/testing/ServiceTestRunner.java
Labels: wip

#2411 [INFINITY-3363] Add custom domain and testing for Kafka security
  frameworks/helloworld/tests/test_custom_service_tld.py
  frameworks/kafka/tests/auth.py
  frameworks/kafka/tests/test_ssl_kerberos_custom_domain_auth.py
  frameworks/kafka/universe/config.json
  frameworks/kafka/universe/marathon.json.mustache
  testing/sdk_hosts.py
Labels: ready for review

#2418 [INFINITY-3363] Skip ZooKeeper reresolution test
  frameworks/kafka/tests/test_zookeeper.py
Labels: ready for review, tests

#2426 [INFINITY-3363] Skip ZooKeeper reresolution test (#2418)
  frameworks/kafka/tests/test_zookeeper.py
Labels: backport, ready for review, tests

#2432 Backport region awareness
  frameworks/helloworld/src/main/java/com/mesosphere/sdk/helloworld/scheduler/Main.java
  frameworks/helloworld/tests/test_region_awareness.py
  frameworks/helloworld/universe/config.json
  frameworks/helloworld/universe/marathon.json.mustache
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/DefaultConfigValidators.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/validate/RegionCannotChange.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/dcos/Capabilities.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultServiceSpec.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/ServiceSpec.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/validation/RegionValidator.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/config/validate/RegionCannotChangeTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/SchedulerBuilderTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/validation/ZoneValidatorTest.java
Labels: backport

#2438 Backport Kafka region awareness (#2402)
  frameworks/kafka/src/main/java/com/mesosphere/sdk/kafka/scheduler/Main.java
  frameworks/kafka/src/test/java/com/mesosphere/sdk/kafka/scheduler/ServiceTest.java
  frameworks/kafka/universe/config.json
  frameworks/kafka/universe/marathon.json.mustache
Labels: backport

#2440 Backport Elastic region awareness (#2415)
  frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/Main.java
  frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java
  frameworks/elastic/universe/config.json
  frameworks/elastic/universe/marathon.json.mustache
Labels: backport
