Repository mesosphere/dcos-commons, pull requests merged in 2018-09, with the labels that each got.

#2643 [DCOS-39710] Investigate kafka acl test failures
  frameworks/kafka/tests/auth.py
Labels: ready for review

#2663 [TESTS] Disable metrics tests on 1.12
  frameworks/cassandra/tests/test_sanity.py
  frameworks/elastic/tests/test_sanity.py
  frameworks/hdfs/tests/test_sanity.py
  frameworks/kafka/tests/test_sanity.py
Labels: ready for review, tests

#2678 [TOOLS] Also persist KDC when deploying
  tools/kdc/kdc.py
Labels: ready for review

#2655 [DCOS-41388] Fix bug where v1 mesos client instantiation defaults to v0
  .gitignore
  build.gradle
  frameworks/cassandra/build.gradle
  frameworks/elastic/build.gradle
  frameworks/hdfs/build.gradle
  frameworks/hdfs/tests/test_sanity.py
  frameworks/helloworld/build.gradle
  frameworks/helloworld/tests/test_zzzrecovery.py
  frameworks/helloworld/tests/tls/keystore/build.gradle
  frameworks/kafka/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  sdk/scheduler/build.gradle
  sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/SchedulerDriverFactory.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/SchedulerConfig.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/FrameworkSchedulerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/SchedulerDriverFactoryTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/TLSEvaluationStageTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/offer/evaluate/security/TLSArtifactsGeneratorTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/DefaultSchedulerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/multi/MultiServiceManagerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/plan/DeploymentStepTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/TLSCleanupStepTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallRecorderTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/scheduler/uninstall/UninstallSchedulerTest.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/storage/PersisterCacheTest.java
  sdk/scheduler/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  settings.gradle
  testing/sdk_tasks.py
Labels: ready for review

#2697 Revert "[DCOS-41803] Add tooling to support the new plugin based CLI …
  Dockerfile
  tools/dcos_login.py
Labels: bug, ready for review, tools

#2696 Fix bugs in test.sh for edge-lb
  test.sh
Labels: ready for review, tools
