Repository mesosphere/dcos-commons, pull requests merged in 2019-07, with the labels that each got.

#3112 [WIP] Add support for scheduler upgrades with new role.
  sdk/scheduler/src/main/java/com/mesosphere/sdk/config/DefaultConfigurationUpdater.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkConfig.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/framework/FrameworkRunner.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/AbstractScheduler.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/DefaultResourceSet.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/NamedVIPSpec.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/PortSpec.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/framework/FrameworkRunnerTest.java
Labels: do not merge, wip

#3045 [DCOS-42593] Batch taskInfo writes
  sdk/scheduler/src/main/java/com/mesosphere/sdk/state/StateStore.java
Labels: do not merge

#3128 [DCOS-55083] Pass more params to setBuildStatus to fix status checks
  Jenkinsfile.dcos-commons
  Jenkinsfile.dcos-commons-base
Labels: ready for review
