Repository mesosphere/dcos-commons, pull requests merged in 2019-06, with the labels that each got.

#2929 Provide a simple 'hello-world' template that's using profile volumes.
  frameworks/helloworld/src/main/dist/profile-mount-volume.yml
  frameworks/helloworld/src/test/java/com/mesosphere/sdk/helloworld/scheduler/ServiceTest.java
  frameworks/helloworld/universe/config.json
Labels: ready for review

#3096 [DCOS-54802] Add fixes for proper RLIMIT_INFINITY support.
  sdk/scheduler/src/main/java/com/mesosphere/sdk/offer/evaluate/PodInfoBuilder.java
  sdk/scheduler/src/main/java/com/mesosphere/sdk/specification/RLimitSpec.java
  sdk/scheduler/src/test/java/com/mesosphere/sdk/specification/RLimitSpecTest.java
Labels: ready for review

#3095 [DCOS-51992] Auditing and changing Non-HTTPS resources & references to HTTPS
  CONTRIBUTING.md
  README.md
  build.gradle
  changelog.md
  docs/README.md
  docs/generate.sh
  docs/pages/developer-guide.md
  docs/pages/faq.md
  docs/pages/yaml-reference.md
  tools/airgap_linter.py
  tools/pip/setup.py
  tools/universe/package_publisher.py
Labels: ready for review

#3046 [DCOS-51637] Add tooling support for submodule-based projects.
  .pre-commit-config.yaml
  frozen_requirements.txt
  pyproject.toml
  run_container.sh
  test.sh
  tools/ci/checks/get_base_branch.sh
  tools/ci/checks/run_pre_commit.sh
  tools/ci/launch_cluster.sh
  tools/ci/steps/check_python_files.sh
  tools/ci/test_runner.sh
Labels: ready for review, tools

#3107 [DCOS-51637] Remove Elastic from dcos-commons.
  .gitignore
  TESTING.md
  frameworks/elastic/README.md
  frameworks/elastic/build-kibana.sh
  frameworks/elastic/build.gradle
  frameworks/elastic/build.sh
  frameworks/elastic/kibana/init.sh
  frameworks/elastic/kibana/nginx.conf.tmpl
  frameworks/elastic/options/custom_name.json
  frameworks/elastic/src/main/dist/elasticsearch.yml
  frameworks/elastic/src/main/dist/install-plugins.sh
  frameworks/elastic/src/main/dist/java-dns-ttl.sh
  frameworks/elastic/src/main/dist/jvm.options
  frameworks/elastic/src/main/dist/setup-java-policy.sh
  frameworks/elastic/src/main/dist/svc.yml
  frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/ElasticZoneValidator.java
  frameworks/elastic/src/main/java/com/mesosphere/sdk/elastic/scheduler/Main.java
  frameworks/elastic/src/main/resources/elasticsearch.yml
  frameworks/elastic/src/main/resources/install-plugins.sh
  frameworks/elastic/src/main/resources/java-dns-ttl.sh
  frameworks/elastic/src/main/resources/setup-java-policy.sh
  frameworks/elastic/src/main/resources/svc.yml
  frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java
  frameworks/elastic/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  frameworks/elastic/tests/__init__.py
  frameworks/elastic/tests/config.py
  frameworks/elastic/tests/conftest.py
  frameworks/elastic/tests/test_custom_options.py
  frameworks/elastic/tests/test_overlay.py
  frameworks/elastic/tests/test_rack_awareness.py
  frameworks/elastic/tests/test_sanity.py
  frameworks/elastic/tests/test_tls.py
  frameworks/elastic/tests/test_upgrade.py
  frameworks/elastic/universe-kibana/config.json
  frameworks/elastic/universe-kibana/marathon.json.mustache
  frameworks/elastic/universe-kibana/package.json
  frameworks/elastic/universe-kibana/resource.json
  frameworks/elastic/universe/config.json
  frameworks/elastic/universe/marathon.json.mustache
  frameworks/elastic/universe/package.json
  frameworks/elastic/universe/resource.json
  frameworks/elastic/upgrade_base_tech.md
  frameworks/elastic/versions.sh
  settings.gradle
  tools/update_config_json.py
Labels: elastic

#3108 [DCOS-51986] Add media attribute to service account and secret settings.
  frameworks/cassandra/universe/config.json
  frameworks/hdfs/universe/config.json
Labels: ready for review
